### ISSUE TITLE
Drop building blocks for font-weight declaration

### ISSUE THREAD

**Issue by denisfrietman** [AanZee/harbour#6]
Here the building blocks method works against convention and makes font-weight declaration harder to use instead of easier.

**Comment by bartvandebiezen** [comment]
One advantage would be if you want to make everything thinner and make e.g. font-weight 300 the new default option. That would be very easy to do. I agree, this won't happen often.

**Comment by jeroenransijn** [comment]
As I understand it the current implementation looks like this:
```scss
$font-weight--100: 400;
$font-weight--200: 500;
$font-weight--300: 600;
$font-weight--400: 700;
$font-weight--500: 800;
$font-weight--600: 900;
```

The advantage of this might be to change it at a later stage without doing it manually. The main flaw with this assumption is that the same variables could be used for different fonts. This different fonts will use the same variables, so changing `$font-weight--100: 400;` could change your headings and body text. Manually checking the code is still the issue here. Essentially it comes down to how to apply modifiers to variables.

## How to apply modifiers to variables
For a modifier to work there needs to be a element to modify. This can't be `$font-weight` since it is more like a namespace than an element. I would suggest creating `elements` first for this kind of variables:
```scss
```
